config/routes.rb
Rails.application.routes.draw do
  devise_for(:users, only: %i[sessions registrations])

  resources :money_transactions, only: %i[new create]

  root 'bank_accounts#show'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bank_account.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: bank_accounts
#
#  id         :bigint           not null, primary key
#  balance    :bigint           default(0), not null
#  user_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class BankAccount < ApplicationRecord
  belongs_to :user

  has_many :sent_transactions, class_name: 'MoneyTransaction',
                               foreign_key: :sender_id,
                               inverse_of: :sender,
                               dependent: :destroy

  has_many :receieved_transactions, class_name: 'MoneyTransaction',
                                    foreign_key: :recepient_id,
                                    inverse_of: :recepient,
                                    dependent: :destroy

  def all_money_transactions
    sent_transactions.or(receieved_transactions).order(created_at: :desc)
  end
end

app/models/money_transaction.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: money_transactions
#
#  id                                  :bigint           not null, primary key
#  sender_id                           :bigint           not null
#  recepient_id                        :bigint           not null
#  amount                              :bigint           not null
#  sender_balance_after_transaction    :bigint           not null
#  recepient_balance_after_transaction :bigint           not null
#  created_at                          :datetime         not null
#  updated_at                          :datetime         not null
#
class MoneyTransaction < ApplicationRecord
  belongs_to :sender, class_name: 'BankAccount'
  belongs_to :recepient, class_name: 'BankAccount'
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                  :bigint           not null, primary key
#  email               :string           not null
#  encrypted_password  :string           not null
#  remember_created_at :datetime
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
class User < ApplicationRecord
  STARTER_BALANCE = 1_000_000_00
  EMAIL_REGEX = /\A[^@\s]+@[^@\s]+\z/

  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_one :bank_account, dependent: :destroy

  after_create :create_bank_account!
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bank_accounts_controller.rb
# frozen_string_literal: true

class BankAccountsController < ApplicationController
  include Pagy::Backend

  before_action :authenticate_user!

  def show
    operation = ::DigiBank::BankAccount::Operation::Show.call(current_user:, params:)

    @operation_result = operation[:result]
  end
end

app/controllers/money_transactions_controller.rb
# frozen_string_literal: true

class MoneyTransactionsController < ApplicationController
  before_action :authenticate_user!

  def new
    @contract = DigiBank::MoneyTransaction::Contract::Create.new
  end

  def create
    result = call_create_operation

    if result[:success?]
      redirect_to root_path, notice: I18n.t('money_transaction.money_sent')
    else
      @contract = result[:contract]

      render 'money_transactions/new'
    end
  end

  private

  def permitted_create_params
    params.require(:money_transaction).permit(:recepient_email, :amount_in_cents)
  end

  def call_create_operation
    DigiBank::MoneyTransaction::Operation::Create.call(
      contract_class: DigiBank::MoneyTransaction::Contract::Create,
      current_user:,
      params: permitted_create_params
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/views/bank_accounts/_header.html.haml
.bg-success.py-3.bg-opacity-75.border.border-success.border-start-0.rounded-end
  .container
    .row
      .col.text-start
        %span.btn.btn-outline-dark.disabled.text-black
          = current_user.email
      .col.text-end
        %span
          = link_to t('bank_account.log_out'), destroy_user_session_path, class: 'text-decoration-none btn btn-outline-dark', id: 'logoutLink'
- if notice
  %p.alert.alert-info.text-center= notice

app/views/bank_accounts/_pagination.html.haml
- if @operation_result[:pagy_cursor].prev.present?
  %a{href: "/?page=#{@operation_result[:pagy_cursor].prev}", class: 'btn btn-outline-dark'}
    = t('pagination.prev')
- else
  %a{href: '#', class: 'disabled btn btn-outline-dark'}
    = t('pagination.prev')

- @operation_result[:pagy_cursor].pages.times do |page|
  - if (page + 1) == @operation_result[:pagy_cursor].page
    %a{href: "/?page=#{page + 1}", class: 'btn btn-outline-dark active'}
      = page + 1
  - else
    %a{href: "/?page=#{page + 1}", class: 'btn btn-outline-dark'}
      = page + 1

- if @operation_result[:pagy_cursor].next.present?
  %a{href: "/?page=#{@operation_result[:pagy_cursor].next}", class: 'btn btn-outline-dark'}
    = t('pagination.next')
- else
  %a{href: '#', class: 'disabled btn btn-outline-dark'}
    = t('pagination.next')

app/views/bank_accounts/_transaction_history.html.haml
%h2
  = t('transaction_history.title')
%table.table.table-hover.table-bordered.mt-4
  %thread
    %tr
      %th{scope: "col"}
        = t('transaction_history.id')
      %th{scope: "col"}
        = t('transaction_history.from')
      %th{scope: "col"}
        = t('transaction_history.to')
      %th{scope: "col"}
        = t('transaction_history.amount')
      %th{scope: "col"}
        = t('transaction_history.balance_after_transaction')
      %th{scope: "col"}
        = t('transaction_history.sent_at')
  %tbody.table-group-divider
    - @operation_result[:money_transactions].each do |money_transaction|
      %tr{class: "#{money_transaction.bootstrap_row_color_class}"}
        %th{scope: "row"}
          = money_transaction.id
        %th
          = money_transaction.sender_email
        %th
          = money_transaction.recepient_email
        %th
          = money_transaction.transfered_amount
        %th
          = money_transaction.balance_after_transaction
        %th
          = money_transaction.created_at
.row
  .col
    = render 'bank_accounts/pagination'

app/views/bank_accounts/show.html.haml
= render 'bank_accounts/header'

.container.mt-5
  .row
    .col-4.text-center
      %h2
        = t('bank_account.balance')
      %h4.mt-4
        = @operation_result[:bank_account].usd_balance
      %a.btn.btn-outline-dark.mt-2{href: new_money_transaction_path}
        = t('bank_account.send_money')
    .col-8.text-center
      = render 'bank_accounts/transaction_history'

app/views/layouts/_flash.html.haml
- if alert
  %p.alert.alert-danger.text-center= alert

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DigiBank
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  %body
    = render 'layouts/flash'
    = yield

app/views/money_transactions/new.html.haml
= render 'bank_accounts/header'

.container.text-center
  .row.mt-5.justify-content-md-center
    .col-md-3
      %h2= t('money_transaction.form_title')
      = form_with(scope: :money_transaction, url: money_transactions_path) do |f|
        .field
          = f.label :recepient_email, class: 'col-form-label'
          - if !@contract.errors.messages.include?(:recepient_email)
            = f.email_field :recepient_email, autofocus: true, class: 'form-control', value: @contract.recepient_email
          - else
            = f.email_field :recepient_email, autofocus: true, class: 'form-control is-invalid', value: @contract.recepient_email
            .invalid-feedback
              - @contract.errors.messages[:recepient_email].each do |error|
                = "#{error}; "
        .field
          = f.label :amount_in_cents, class: 'col-form-label'
          - if !@contract.errors.messages.include?(:amount_in_cents)
            = f.text_field :amount_in_cents, autofocus: true, class: 'form-control', value: @contract.amount_in_cents
          - else
            = f.text_field :amount_in_cents, autofocus: true, class: 'form-control is-invalid', value: @contract.amount_in_cents
            .invalid-feedback
              - @contract.errors.messages[:amount_in_cents].each do |error|
                = "#{error}; "
        .actions.mt-3
          = f.submit t('money_transaction.send'), class: 'btn btn-outline-dark px-4 me-1'
          %a.btn.btn-outline-dark.px-4.ms-1{href: root_path(@current_user)}
            = t('money_transaction.cancel')